version: "3.8"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=secret
        POSTGRES_USER=root
        POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
